config/routes.rb
Rails.application.routes.draw do
  resources :employees
  resources :departments
  devise_for :users
  root 'departments#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
  belongs_to :user
  has_many :employees
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :department
end

app/models/user.rb
class User < ApplicationRecord
  has_many :departments
  has_many :employees, through: :departments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
	def configure_permitted_parameters 
      devise_parameter_sanitizer.permit(:sign_up, keys: [:rif, :name, :email, :password, :remember_me])
      devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :password, :remember_me])
    end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :destroy, :index]
  # GET /departments
  # GET /departments.json
  def index
    @departments = current_user.departments
    @department = Department.new
  end

  # GET /departments/1
  # GET /departments/1.json
  def show
    @employees = @department.employees
    @employee = Employee.new
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, notice: 'Department was successfully created.' }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1
  # PATCH/PUT /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to @department, notice: 'Department was successfully updated.' }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department.destroy
    respond_to do |format|
      format.html { redirect_to departments_url, notice: 'Department was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    def department_params
      params.require(:department).permit(:name, :user_id)
    end

    def set_user
    @user = current_user
   end
    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:first_name, :last_name, :ci, :phone_number, :email, :bank, :account_type, :count_number, :landline, :emergency_phone, :department_id)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = current_user.employees.where(["first_name LIKE ?","%#{params[:search]}%"])
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @department = Department.find(@employee.department_id)
  end

  # GET /employees/new
  def new
    @department = Department.find(@employee.department_id)
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
    @department = Department.find(@employee.department_id)
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)
    respond_to do |format|
      if @employee.save
        format.html { redirect_to Department.find(@employee.department_id), notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new, notice: 'Employee was not successfully created.' }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to Department.find(@employee.department_id), notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @department = Department.find(@employee.department_id)
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to @department, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:first_name, :last_name, :ci, :phone_number, :email, :bank, :account_type, :count_number, :landline, :emergency_phone, :department_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # User callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :rif, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/departments/_employee_filter.html.erb
  <%= form_tag employees_path, class: 'd-block', :method => 'get' do %>
  <div class="form-group row employee_filter p-2">
  	<div class="col-8">
  	  <%= text_field_tag :search, params[:search], class:'form-control', placeholder:'Busqueda de empleados' %>
  	</div>
  	<div>
  	  <%= submit_tag "icono", class: 'button btn btn-primary' %> 	
  	</div> 
  	<div class="float-right">
  	  <%= link_to('Cerrar sesión', destroy_user_session_path, method: :delete, class: 'button btn btn-primary') %>
  	</div>     
  </div>
<% end %>

<br>

app/views/departments/_form.html.erb
<%= form_with(model: department, local: true) do |form| %>
  <div class="row">
    <div class="col border p-3">
      <div class="field mb-3 form-group">
        <%= form.label 'Nombre del departamento' %>
        <br>
        <%= form.text_field :name, id: :department_name, class: 'input-group' %>
      </div>

      <div class="field hidden form-group">
        <%= form.text_field :user_id, id: :department_user_id, value: current_user.id %>
      </div>

      <div class="actions">
        <%= form.submit class: 'btn btn-primary btn-block' %>
      </div>
    </div>
  </div>
<% end %>
 

app/views/departments/_notice.html.erb
<% if notice %>
  <div class="row justify-content-center text-center">
	<div class="col-7 alert alert-success alert-dismissible">
	  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a> <%= notice %>
    </div>        
  </div>
<% end %>

app/views/departments/edit.html.erb
<div class="row justify-content-center">
  <div class="col-5">
  	<h1>Editando departamento	</h1>
	<%= render 'form', department: @department %>

	<%= link_to 'Show', @department %> |
	<%= link_to 'Back', departments_path %>  	
  </div>	
</div>

app/views/departments/index.html.erb
<%= render partial: "employee_filter" %>
<%= render partial: "notice" %>
<div class="row justify-content-center">
  <div class="col-8 justify-content-center">
    <h2>Departamentos</h2>
    <% if current_user.departments.count == 0%>
      <div class="row justify-content-center">
        <div class="col-12" align="center">
          <img src="<%= asset_path 'vacio.png' %>">          
        </div>
      <br>
      <br>
        <h4>Aún no hay departamentos</h4>
        <div>
          Puedes crear tu primer departamento utilizando el siguiente formulario:
        </div>
      </div>
      
    <% else %>
      <table class="border d-block" cellpadding="10">
        <thead>
          <tr class="text-center">
            <th>Nombre del departamento</th>
            <th>Cantidad de empleados</th>
            <th>Acciones</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        
        <tbody>
          <% @departments.each do |department| %>
            <tr>
              <td><%= link_to "#{department.name}",department_path(department) %></td>
              <td class="text-center"><%= department.employees.count %></td>
              <td class="text-justify"><%= link_to 'Edit', edit_department_path(department) %> 
              <%= link_to 'Destroy', department, method: :delete, data: { confirm: 'Are you sure?' } %></td>            
            </tr>
          <% end %>
        </tbody>
      </table>
      <br>
    <% end %>
  </div>
  <div class="col-3">
    <h2>New Department</h2>
    <%= render 'form', department: @department %>
  </div>   
</div>

app/views/departments/new.html.erb
<h1>Nuevo departamento</h1>

<%= render 'form', department: @department %>

<%= link_to 'Back', departments_path %>

app/views/departments/show.html.erb
<%= render partial: "employee_filter" %>
<%= render partial: "notice" %>
<div class="row justify-content-center">
  <div class="col-7">
    <h2><span><%= link_to '<', departments_path %></span> Empleados de <%= @department.name %></h2>
    <% if @department.employees.count == 0%>
      <div class="row justify-content-center">
        <div class="col-12" align="center">
          <img src="<%= asset_path 'vacio.png' %>">          
        </div>
      <br>
      <br>
        <h4 class="col-12 text-center">Aún no hay empleados</h4>
        <div class="text-center">
          Puedes crear tu primer empleado utilizando el siguiente formulario:
        </div>
      </div>

    <% else %>
      <div class="row ">
        <table cellpadding="20" class="border">
          <thead class="border">
            <tr>
              <th class="pr-5">Cédula</th>
              <th class="pr-5">Nombre</th>
              <th class="pr-5 pl-5">Celular</th>
              <th class="pl-5">Acciones</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          
          <tbody>
            <% @employees.each do |employee| %>
              <tr>
                <td><%= employee.ci %></td>
                <td><%= employee.first_name %></td>
                <td class="pl-5"><%= employee.phone_number %></td>
                <td class="text-justify"><%= link_to 'Edit', edit_employee_path(employee)%> 
                <%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>            
              </tr>
            <% end %>
          </tbody>
        </table>
      
      </div>
      <br>
    <% end %>
  </div>
  <div class="col-4">
    <h2>Nuevo empleado</h2>
    <%= render './employees/employee_form', employee: @employee %>
  </div>   
</div>

app/views/employees/_employee_form.html.erb
<%= form_with(model: @employee, local: true) do |form| %>
  <div class="row justify-content-center">
    <div class="field mb-3 form-group col-6">
      <%= form.label 'Nombre*', class: 'font-weight-bold' %>
      <%= form.text_field :first_name, id: :employee_first_name, class: 'form-control' %>
    </div>

    <div class="field mb-3 form-group col-6">
      <%= form.label 'Apellido*', class: 'font-weight-bold'%>
      <%= form.text_field :last_name, id: :employee_last_name, class: 'form-control' %>
    </div>
  </div>

  <div class="row justify-content-center">

    <div class="field mb-3 form-group col-6">
      <%= form.label 'Cédula*', class: 'font-weight-bold' %>
      <%= form.text_field :ci, id: :employee_ci, class: 'form-control' %>
    </div>

    <div class="field mb-3 form-group col-6">
      <%= form.label 'celular*', class: 'font-weight-bold' %>
      <%= form.text_field :phone_number, id: :employee_phone_number, class: 'form-control' %>
    </div>

  </div>

    <div class="field mb-3 form-group">
      <%= form.label 'Correo electrónico' %>
      <%= form.text_field :email, id: :employee_email, class: 'form-control' %>
    </div>
  <div class="row justify-content-center">

    <div class="field mb-3 form-group col-6">
      <%= form.label 'Banco'%>
      <%= form.text_field :bank, id: :employee_bank, class: 'form-control' %>
    </div>

    <div class="field mb-3 form-group col-6">
      <%= form.label 'Tipo de cuenta' %>
      <%= form.text_field :account_type, id: :employee_account_type, class: 'form-control' %>
    </div>
  </div>

    <div class="field mb-3 form-group">
      <%= form.label 'Nro de cuenta' %>
      <%= form.text_field :count_number, id: :employee_count_number, class: 'form-control' %>
    </div>

  <div class="row justify-content-center">

    <div class="field mb-3 form-group col-6">
      <%= form.label 'Fijo' %>
      <%= form.text_field :landline, id: :employee_landline, class: 'form-control' %>
    </div>

    <div class="field mb-3 form-group col-6">
      <%= form.label 'Emergencia' %>
      <%= form.text_field :emergency_phone, id: :employee_emergency_phone, class: 'form-control' %>
    </div>
  </div>

  <div class="hidden">
    <%= form.text_field :department_id, id: :department_user_id, value: @department.id %>
  </div>
  <div class="actions">
    <%= form.submit class: 'btn btn-primary btn-block' %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'employee_form', employee: @employee %>

<%= link_to 'Back', @department %>

app/views/employees/index.html.erb
<%= render partial: "./departments/employee_filter" %>
<div class="row justify-content-center">
  <div class="col-8">
    <h2><span><%= link_to '<', departments_path %></span> Resultados de la búsqueda</h2>
    <% if current_user.employees.count == 0%>
      <div class="row justify-content-center">
        <div class="col-12" align="center">
          <img src="<%= asset_path 'vacio.png' %>">          
        </div>
      <br>
      <br>
        <h4 class="col-12 text-center">Aún no hay empleados</h4>
      </div>

    <% else %>
      <table class="border d-block" cellpadding="10">
        <thead>
          <tr class="text-center">
            <th>Nombre del departamento</th>
            <th>Cantidad de empleados</th>
            <th>Acciones</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        
        <tbody>
          <% @employees.each do |employee| %>
            <tr>
              <td><%= employee.first_name %></td>
              <td class="text-center"><%= 'Aqui va algo' %></td>
              <td class="text-justify"><%= link_to 'Edit', edit_employee_path(employee)%> 
              <%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>            
            </tr>
          <% end %>
        </tbody>
      </table>
      <br>
    <% end %>
  </div>  
</div>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'employee_form', employee: @employee %>

<%= link_to 'Back', departments_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @employee.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @employee.last_name %>
</p>

<p>
  <strong>Ci:</strong>
  <%= @employee.ci %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @employee.phone_number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employee.email %>
</p>

<p>
  <strong>Bank:</strong>
  <%= @employee.bank %>
</p>

<p>
  <strong>Account type:</strong>
  <%= @employee.account_type %>
</p>

<p>
  <strong>Count number:</strong>
  <%= @employee.count_number %>
</p>

<p>
  <strong>Landline:</strong>
  <%= @employee.landline %>
</p>

<p>
  <strong>Emergency phone:</strong>
  <%= @employee.emergency_phone %>
</p>

<p>
  <strong>Department:</strong>
  <%= @employee.department.name %>
</p>

<%= link_to 'Back', @department %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <% if user_signed_in? %>
      <title><%= current_user.name %></title>
    <% else %>
      <title>Inicio</title>
    <% end %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">      
      <%= yield %>      
    </div>
  </body>
</html>